let levelVariable = new Level(
  [
    new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    new LitteChicken(),
    // new LitteChicken(),
    // new LitteChicken(),
    // new LitteChicken(),
    // new LitteChicken(),
    // new LitteChicken(),
  ],
  [
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
  ],
  [
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
  ],
  [
    new Cloud(), new Cloud()
  ],
  [
    new Background("img/5_background/layers/air.png", 0),
    new Background("img/5_background/layers/3_third_layer/1.png", 0),
    new Background("img/5_background/layers/2_second_layer/1.png", 0),
    new Background("img/5_background/layers/1_first_layer/1.png", 0),
    new Background("img/5_background/layers/air.png", 719),
    new Background("img/5_background/layers/3_third_layer/2.png", 719),
    new Background("img/5_background/layers/2_second_layer/2.png", 719),
    new Background("img/5_background/layers/1_first_layer/2.png", 719),
    new Background("img/5_background/layers/air.png", 1438),
    new Background("img/5_background/layers/3_third_layer/1.png", 1438),
    new Background("img/5_background/layers/2_second_layer/1.png", 1438),
    new Background("img/5_background/layers/1_first_layer/1.png", 1438),
  ]
);
